[project]
name = "yolo-12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "easydict",
    "ipykernel",
    "ultralytics",
    "lap",
    "flask",
]
